#=================================================
# Origin: https://github.com/P3TERX/Actions-OpenWrt
# Author: P3TERX
# Blog: https://p3terx.com
# Lisence: MIT
# Description: Build OpenWrt using GitHub Actions
# Modified by: Mardeson
# Blog: https://mardeson.wang
#=================================================
name: TEST

on:
#  schedule:
#    - cron: 0 20 * * 6
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Clone source code
      env:
        REPO_URL: https://github.com/Lienol/openwrt
        REPO_BRANCH: dev-19.07
      run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          echo $(date +%y%m%d)_OpenWrt-self-build-Lienol-1907_KSG1218-K2a > name.txt
          fname=$(date +%y%m%d)_OpenWrt-self-build-Lienol-1907_KSG1218-K2a
          echo $fname

    - name: Upload Artifact
      env: 
        FNAME1: $(date +%y%m%d)
      uses: actions/upload-artifact@master
      with:
        name: 123
        path: ./openwrt/config
