#=================================================
# Origin: https://github.com/P3TERX/Actions-OpenWrt
# Author: P3TERX
# Blog: https://p3terx.com
# Lisence: MIT
# Description: Build OpenWrt using GitHub Actions
# Modified by: Mardeson
# Blog: https://mardeson.wang
#=================================================
name: TEST

on:
#  schedule:
#    - cron: 0 20 * * 6
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          echo $(date +%y%m%d)_OpenWrt-self-build-Lienol-1907_KSG1218-K2a > name.txt
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

    - name: Clone source code
      env:
        REPO_URL: https://github.com/Lienol/openwrt
        REPO_BRANCH: dev-19.07
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: name.txt
        path: ./openwrt
